#!/bin/bash

DEPLOY_PATH="/home/yuliang/githook"
TOKEN_PATH="/etc/environment.githook"

EXEC="/usr/bin/ruby"
PIDFILE="/var/run/githook.pid"
SCRIPT="$DEPLOY_PATH/server.rb"
LOG="$DEPLOY_PATH/server.log"

function start_service {
    echo Starting Service...
    cd $DEPLOY_PATH
    source $TOKEN_PATH
    start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --chdir . --startas $EXEC -- $SCRIPT >> $LOG 2>&1 &
}

function stop_service {
    echo Stop Service...
    cd $DEPLOY_PATH; start-stop-daemon --stop --pidfile $PIDFILE --retry TERM/30/KILL/5
}

function usage {
    echo "Usage:"
    echo -e "\t`basename $0` {start|stop|restart}"
}

if [ -z "$1" ]; then
    usage
elif [ "$1" == "start" ]; then
    start_service
elif [ "$1" == "stop" ]; then
    stop_service
elif [ "$1" == "restart" ]; then
    stop_service
    start_service
else
    usage
fi

